# Generated by Django 4.1.5 on 2023-02-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
